### PR TITLE
Release 34.0

### PR DESCRIPTION
**Pull request by di**

### CODE REVIEW

**Comment by miketheman** [comment]
🎉 @di is there something that needs to happen for this release to show up on https://github.com/pypa/readme_renderer/releases ?

**Comment by di** [comment]
@miketheman Yeah, I need to remember to tag the release 😅. Want to try to fix https://github.com/pypa/readme_renderer/issues/232?

**Comment by miketheman** [comment]
Thanks! I'm game to look at the other issue - but that's worded to follow a tag/release creation - what happens if $Human forgets to create the tag?

Or is the intent "$Human creates a tag, and then an artifact is uploaded to pypi automatically"?

**Comment by di** [comment]
> Or is the intent "$Human creates a tag, and then an artifact is uploaded to pypi automatically"?

Yep!

**Pull request merged**
