### PR TITLE
Remove py2-specific dependencies and fix tests

### PR DESCRIPTION
**Pull request by mgorny**
1. Fix GitHub actions to actually test against the requested Python version (rather than 2.7 everywhere).
2. Replace external `mock` with py3's `unittest.mock`.
3. Remove dependency on `six`.
4. Use the new `pytest` executable name.

### CODE REVIEW

**Comment by mgorny** [comment]
I dare say the tests are using Python 2.7 instead of the Python they were supposed to test.

**Comment by mgorny** [comment]
I'm going to experiment a little trying to fix it.

**Comment by mgorny** [comment]
Ok, it's ready for review now.

**Comment by di** [comment]
Great catch, thanks!

**Pull request merged**
