### PR TITLE
Include docinfo when rendering rst

### LINKED ISSUE #61: Include docinfo table
I'm used to put standard docinfo in my README.rst and thus in package's description.

The `rst.render()` function considers only the `fragment`, though, so that information does not appear on PyPI/Warehouse.

To trick it I indent the docinfo fields, so that they are rendered as a `<table>` within a `<blockquote>`: that works, but the result is somewhat ugly.

What do you think about prepending the `docinfo` part, if present?

### PR DESCRIPTION
**Pull request by theacodes**
Closes #61.

Screenshot of docinfo on Warehouse:

screen shot 2018-04-20 at 10 47 51 am

### CODE REVIEW

**Comment by di** [comment]
Would it make sense to put the docinfo at the _end_ of the rendered description, rather than at the beginning?

**Comment by jonparrott** [comment]
Possibly, but we'd be breaking precedence with literally every other rst renderer (docutils, sphinx, and github).

**Comment by di** [comment]
Well, we already are by only rendering the fragment. My concern is that most users reading a projects description probably want to read the first couple lines of the description, not all this metadata. We've already gotten some complaints that there is not enough information density on small screens, and I think this might aggravate it.

I think it might also be unclear to users that this metadata is coming from the description, and not from PyPI itself. For example, in your screenshot, the date of the "created" line is pretty much always going to disagree with the release date. At least in this example, a lot of this information (license, author, project name) is already going to be included in the sidebar on PyPI anyways as well.

I'd like to hear what others (@dstufft, @ewdurbin) think.

**Comment by jonparrott** [comment]
Totally fair points. Definitely interested to see what others say.

**Comment by theacodes** [comment]
After discussing with @dstufft and @di in person, we decided to merge this as-is. Although this isn't pretty, we don't want to deviate from how GitHub renders things. Additionally, this is optional and present on a fairly small number of readmes.

**Pull request merged**
