### PR TITLE
Make Python 3 the default lexer for highlighting Python code in Markdown

### LINKED ISSUE #96: Python 3.5 new keywords, async and await, not syntax highlighted
From https://github.com/pypa/warehouse/issues/3770:

> See for instance https://pypi.org/project/influxdbpusher/
>
> It has code snippets  with `async def` and `await`, which are not being properly highlighted as keywords.

### PR DESCRIPTION
**Pull request by jonparrott**
Fixes #96

### CODE REVIEW

**Comment by di** [comment]
I'm not sure we want to introduce a shortname (`python2`) that doesn't actually exist in pygments. I'm also hesitant to add anything that produces inconsistencies between how these READMEs are rendered on PyPI and how they're rendered elsewhere (e.g. on Github), which is what will happen if folks use the `python` shortname with this PR.

Perhaps the original issue is actually invalid, and we should tell users that want to highlight Python 3 code that they should use the `python3` shortname? I agree that `python` should probably map to the Python 3 lexer _someday_, but I'm not sure if it's for us to decide.

**Comment by jonparrott** [comment]
Yeah I'm hestant here, but I can think of some arguments *in favor* of doing this.

The biggest is that GitHub's highlighter defaults `python` to `python3` for example this is just `python` after the code fence:

```python
async def meep():
   pass

await meep()
```

Since the goal of supporting `gfm` is to be as close to github as possible, I am okay with us aliasing `python` to `python3`. Especially because without aliasing there's no way to get highlighting to work correctly for Python 3 code on both github and warehouse at the same time.

Whether or not we should allow `python2` to work is another story. I wanted at least *some* sort of escape hatch in case some user really, really needed Python 2 highlighting mode. But, I'm happy to leave that out until someone asks for it.

**Comment by di** [comment]
Ah, I didn't realize GFM was already mapping `python`->`python3`. In that case, we probably should as well.

**Comment by jonparrott** [comment]
> Let's ditch the python2 shortname.

Done.

**Pull request merged**
