### PR TITLE
Add support for GFM task list items

### PR DESCRIPTION
**Pull request by jboarman**
This PR is designed to add support for TODO lists that are provided by [Github Flavored Markdown](https://github.github.com/gfm/#task-list-items-extension-).

The GFM renderer already provides this support.  However, the `clean` operation was filtering out the resulting rendered HTML `input` tags.

To safely add this support, a `disabled` attribute is forced to be added to any rendered HTML `input` tags.

Now, TODO list items are properly rendered from the output of `cmarkgfm.github_flavored_markdown_to_html`.

**Example GFM task list that can now be rendered from a README:**
* [X] Add support for GFM task list items
* [ ] Hide bullets currently rendered by `cmarkgfm` for todo list items

### CODE REVIEW

**Review by Ely68 — APPROVED** [review]
tnx

**Review by Ely68 — APPROVED** [review]

**Comment by McSinyx** [comment]
cmarkgfm 0.6.0 has been released earlier this month.  Could you check for the compatibility while you're working on this PR?

**Comment by jboarman** [comment]
Thanks @McSinyx for mentioning the updated `cmarkgfm` release.

The [latest `cmarkgfm` release](https://github.com/theacodes/cmarkgfm/releases/tag/0.6.0) makes an adjustment to how code blocks are rendered by removing CSS class assignments and favoring a `lang` attribute instead.  The language-oriented CSS classes do not currently seem to be in use by PyPI, so this change should not have any impact.

**Comment by McSinyx** [comment]
I noticed this because readme-renderer is pinning cmarkgfm
by its the minor version and I'm packaging downstream with
a single-versioning policy so I could not upgrade cmarkgfm
with the current readme-renderer.  Could you try to relax
the specifier?

**Comment by jboarman** [comment]
Sorry to hear about the issue you are encountering @McSinyx.  It sounds like this needs to be addressed in a separate PR.  Can you issue that PR?

**Comment by mondeja** [comment]
This has been added in #217

**Pull request closed without merging**
